name: ${name}
version: ${version}
api-version: 26.1
author: Block_Bring
main: top.imbring.playerwaypoints.PlayerWaypointsPlugin

commands: { }

permissions:
  playerwaypoints.create:
    description: 创建路径点
    default: true
  playerwaypoints.del:
    description: 删除路径点
    default: true
  playerwaypoints.del.other:
    description: 删除其他玩家创建的公有路径点
    default: op
  playerwaypoints.info:
    description: 查看路径点信息
    default: true
  playerwaypoints.tp:
    description: 传送至路径点
    default: true
  playerwaypoints.reload:
    description: 重载插件配置文件
    default: op
  playerwaypoints.*:
    description: 所有 playerwaypoints 权限
    default: op
    children:
      playerwaypoints.create: true
      playerwaypoints.del: true
      playerwaypoints.del.other: true
      playerwaypoints.info: true
      playerwaypoints.tp: true
      playerwaypoints.reload: true
